export const Cards = [
  {
    name: "Fairly used component",
    id: "PL0S2502E99V",
    created_at: "07-09-21",
    status: "Pending",
    price: "N25,000",
    payment_url: "https://mui.com/components/material-icons/?query=copy",
  },
  {
    name: "Fairly used component",
    id: "PL0S2502E99V",
    created_at: "07-09-21",
    status: "Locked",
    price: "N25,000",
    payment_url: "https://mui.com/components/material-icons/?query=copy&theme=",
  },
  {
    name: "Fairly used component",
    id: "PL0S2502E99V",
    created_at: "07-09-21",
    status: "Pending",
    price: "N25,000",
    payment_url: "https://mui.com/components/material-icons",
  },
  {
    name: "Fairly used component",
    id: "PL0S2502E99V",
    created_at: "07-09-21",
    status: "Locked",
    price: "N25,000",
    payment_url: "https://mui.com/components/material-icons=copy&theme=Rounded",
  },
  {
    name: "Fairly used component",
    id: "PL0S2502E99V",
    created_at: "07-09-21",
    status: "Refunded",
    price: "N25,000",
    payment_url: "https://mui.com/components/?query=copy&theme=Rounded",
  },
  {
    name: "Fairly used component",
    id: "PL0S2502E99V",
    created_at: "07-09-21",
    status: "Credited",
    price: "N25,000",
    payment_url:
      "https://mui.com/components/material-icons/?query=copy&theme=Rounded",
  },
];
export const states = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT - Abuja",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
];
